### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by jairocedenoadrian** [ggreen86/VFP-Editors#2]
Hello, I would like to know what are the prerequisites, and what is the installation and use process, I do not see an explanation of such a matter! ..
Thanks!

**Comment by ggreen86** [comment]
I will add some information on the installation process later this week.

________________________________
From: Jairo Cedeño Adrián ***@***.***>
Sent: Monday, May 10, 2021 1:43 PM
To: ggreen86/VFP-Editors ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ggreen86/VFP-Editors] Installation (#2)


Hello, I would like to know what are the prerequisites, and what is the installation and use process, I do not see an explanation of such a matter! ..
Thanks!

**Comment by ggreen86** [comment]
Sorry for the long time for response; my time has been limited.  I have uploaded the dependencies for the ActiveX components and added guidance to the end of the README.md file on the usage.  Please see this.  If still have problems, please open a new issue.
